-- Generated by scripts/build-seed.mjs. Edit the JSON in data-official/, not this file.

insert into items (code, name, variant, category, description, specs, qty_total, qty_available, bench_only) values
  ('ARTL-MC-001', 'Arduino Uno', 'R3', 'Microcontroller', 'ATmega328P development board. The lab''s default starting point for anything with a sensor on it.', '[{"label":"MCU","value":"ATmega328P"},{"label":"Logic","value":"5 V"},{"label":"Flash","value":"32 KB"}]'::jsonb, 12, 12, false),
  ('ARTL-MT-014', 'DC Motor', '300 rpm', 'Motor', 'Geared DC motor. Six of these drive MiniRover-1.', '[{"label":"Speed","value":"300 rpm"},{"label":"Supply","value":"12 V"}]'::jsonb, 6, 4, false),
  ('ARTL-SN-022', 'HC-05', 'Bluetooth', 'Module', 'Serial Bluetooth module. The rover''s wireless migration depends on these.', '[{"label":"Profile","value":"SPP"},{"label":"Baud","value":"9600 default"}]'::jsonb, 2, 2, false),
  ('ARTL-PW-007', 'LiPo', '11.1 V 2200 mAh', 'Power', '3S lithium polymer pack. Charge on the bench, never unattended.', '[{"label":"Cells","value":"3S"},{"label":"Capacity","value":"2200 mAh"}]'::jsonb, 3, 0, false),
  ('ARTL-SW-003', 'DPDT', 'Switch', 'Component', 'Double pole double throw. Used for the wired rover control.', '[]'::jsonb, 8, 8, false),
  ('ARTL-TL-031', 'Oscilloscope', '100 MHz', 'Instrument', 'Bench oscilloscope. Lab use only, not for loan off-site.', '[{"label":"Bandwidth","value":"100 MHz"},{"label":"Channels","value":"2"}]'::jsonb, 1, 1, true),
  ('ARTL-MT-020', 'Servo', 'MG996R', 'Motor', 'High-torque metal gear servo.', '[{"label":"Torque","value":"11 kg·cm"},{"label":"Supply","value":"6 V"}]'::jsonb, 6, 6, false),
  ('ARTL-MC-009', 'Raspberry Pi', '4B', 'Microcontroller', 'Single board computer, 4 GB. Runs the vision experiments.', '[{"label":"RAM","value":"4 GB"},{"label":"SoC","value":"BCM2711"}]'::jsonb, 3, 3, false),
  ('ARTL-SN-005', 'Ultrasonic', 'HC-SR04', 'Sensor', 'Ultrasonic range finder.', '[{"label":"Range","value":"2–400 cm"}]'::jsonb, 11, 11, false),
  ('ARTL-MC-015', 'ESP32', 'DevKit v1', 'Microcontroller', 'Wi-Fi and Bluetooth on one die. Preferred over the Uno when anything needs a network.', '[{"label":"Cores","value":"2 × 240 MHz"},{"label":"Radio","value":"Wi-Fi + BLE"}]'::jsonb, 8, 5, false),
  ('ARTL-MC-022', 'STM32', 'Nucleo F401RE', 'Microcontroller', 'ARM Cortex-M4 board for work that has outgrown the AVR.', '[{"label":"Core","value":"Cortex-M4"},{"label":"Clock","value":"84 MHz"}]'::jsonb, 4, 4, false),
  ('ARTL-SN-011', 'IMU', 'MPU-6050', 'Sensor', 'Six-axis accelerometer and gyroscope. Attitude sensing for the rover and the drone rigs.', '[{"label":"Axes","value":"6"},{"label":"Bus","value":"I²C"}]'::jsonb, 9, 2, false),
  ('ARTL-SN-018', 'LiDAR', 'RPLIDAR A1', 'Sensor', '360° laser scanner used for the mapping experiments. Booked out most weeks.', '[{"label":"Range","value":"12 m"},{"label":"Rate","value":"5.5 Hz"}]'::jsonb, 1, 0, false),
  ('ARTL-SN-030', 'Depth Camera', 'Intel RealSense D435', 'Sensor', 'Stereo depth camera. Sign-out requires a coordinator present.', '[{"label":"Depth FOV","value":"87° × 58°"}]'::jsonb, 1, 1, false),
  ('ARTL-MT-027', 'Brushless Motor', 'A2212 1000 KV', 'Motor', 'Outrunner for the fixed-wing and quadrotor airframes.', '[{"label":"KV","value":"1000"}]'::jsonb, 12, 8, false),
  ('ARTL-MT-033', 'ESC', '30 A', 'Motor', 'Electronic speed controller, matched to the A2212.', '[]'::jsonb, 12, 9, false),
  ('ARTL-MT-041', 'Stepper', 'NEMA 17', 'Motor', 'Bipolar stepper for the plotter and the gantry rig.', '[{"label":"Step","value":"1.8°"}]'::jsonb, 10, 10, false),
  ('ARTL-PW-014', 'Bench Supply', '0–30 V 5 A', 'Power', 'Variable bench supply. Two channels, current limited.', '[]'::jsonb, 2, 2, true),
  ('ARTL-PW-021', 'LiPo Charger', 'iMAX B6', 'Power', 'Balance charger. Never leave a pack on it unattended.', '[]'::jsonb, 2, 1, false),
  ('ARTL-TL-004', 'Soldering Station', 'Hakko FX-888D', 'Instrument', 'Temperature-controlled iron. Four stations on the main bench.', '[]'::jsonb, 4, 3, true),
  ('ARTL-TL-012', 'Multimeter', 'Fluke 117', 'Instrument', 'True-RMS handheld. Sign out for field testing.', '[]'::jsonb, 5, 2, false),
  ('ARTL-TL-019', 'Logic Analyser', '8-channel', 'Instrument', 'USB logic analyser for bus debugging.', '[{"label":"Channels","value":"8"},{"label":"Rate","value":"24 MS/s"}]'::jsonb, 2, 2, false),
  ('ARTL-TL-040', '3D Printer', 'Prusa MK4', 'Instrument', 'FDM printer. Queue is managed by the lab manager, not by loan.', '[{"label":"Volume","value":"250 × 210 × 220 mm"}]'::jsonb, 2, 1, true),
  ('ARTL-TL-047', 'Rotary Tool', 'Dremel 4000', 'Instrument', 'Cutting and finishing. Eye protection is not optional.', '[]'::jsonb, 3, 3, false),
  ('ARTL-MD-008', 'Motor Driver', 'L298N', 'Module', 'Dual H-bridge. The rover''s original drive stage.', '[]'::jsonb, 14, 11, false),
  ('ARTL-MD-016', 'GPS Module', 'NEO-6M', 'Module', 'UART GPS receiver with a patch antenna.', '[]'::jsonb, 4, 4, false),
  ('ARTL-MD-025', 'LoRa Module', 'SX1278 433 MHz', 'Module', 'Long-range telemetry for the field trials.', '[{"label":"Band","value":"433 MHz"}]'::jsonb, 6, 3, false),
  ('ARTL-CM-002', 'Breadboard', '830 point', 'Component', 'Full-size solderless breadboard.', '[]'::jsonb, 24, 19, false),
  ('ARTL-CM-009', 'Jumper Set', 'M-M / M-F / F-F', 'Component', 'Assorted jumper leads, 120 per set.', '[]'::jsonb, 20, 20, false),
  ('ARTL-CM-017', 'Resistor Kit', 'E12, 1/4 W', 'Component', 'Full E12 decade set, 600 pieces.', '[]'::jsonb, 6, 6, false),
  ('ARTL-AE-001', 'Airframe', '450 mm quad', 'Airframe', 'Carbon quadrotor frame for the aerial trials.', '[]'::jsonb, 3, 1, false),
  ('ARTL-AE-006', 'Flight Controller', 'Pixhawk 4 mini', 'Airframe', 'Autopilot for the quad and the fixed-wing testbed.', '[]'::jsonb, 2, 2, false),
  ('ARTL-AE-013', 'Propeller Set', '1045', 'Airframe', 'Balanced 10 × 4.5 props, four per set.', '[]'::jsonb, 15, 12, false)
on conflict (code) do update set name = excluded.name, variant = excluded.variant, category = excluded.category, description = excluded.description, specs = excluded.specs, bench_only = excluded.bench_only;

insert into projects (slug, title, subtitle, body, tags, year, sort_order, published) values
  ('minirover-1', 'MiniRover-1', 'rocker-bogie', 'Six-wheeled rover on a rocker-bogie mechanism. When one rocker arm rises the differential drives the other down, holding the chassis level across ground that would tip a rigid frame. At least four wheels stay in contact at all times. Six 300 RPM motors, DPDT wired control, migrating to HC-05 Bluetooth. The next revision targets gesture control via OpenCV.', array['Rocker-bogie', '300 RPM ×6', 'DPDT control', 'HC-05 next']::text[], 2026, 1, true),
  ('differential-linkage-rig', 'Differential linkage rig', 'test bench', 'Bench rig built to prove the differential before it ever went on the rover. Balances motion between left and right rockers and keeps the body stable.', array['Mechanism', 'Test rig']::text[], 2026, 2, true),
  ('gesture-control', 'Gesture control', 'computer vision', 'A computer-vision layer that reads hand gestures and maps them to drive commands. The next revision targets full autonomy.', array['OpenCV', 'Machine learning', 'In progress']::text[], 2026, 3, true),
  ('wireless-drive-stack', 'Wireless drive stack', 'HC-05 migration', 'Migration from wired DPDT switching to Bluetooth control over HC-05, keeping the same motor-driver topology.', array['HC-05', 'Embedded C']::text[], 2026, 4, true)
on conflict (slug) do nothing;

insert into events (external_id, title, starts_at, description, link_url, published) values
  ('69640c109ca5d7968fed571d', 'Development Hackathon', '2025-12-28T00:00:00.000Z', null, null, true),
  ('69640bd59ca5d7968fed5715', 'MLCodefest', '2026-01-10T00:00:00.000Z', null, 'https://unstop.com/hackathons/mlcodefest-indian-institute-of-technology-iit-jodhpur-1602702', true),
  ('69640bb29ca5d7968fed5711', 'Cryptic Hunt', '2026-01-10T00:00:00.000Z', null, 'https://unstop.com/competitions/cryptic-hunt-prometeo26-indian-institute-of-technology-iit-jodhpur-1602891', true),
  ('69640b009ca5d7968fed56f9', 'CADastra', '2026-01-10T00:00:00.000Z', null, 'https://unstop.com/competitions/cadastra-indian-institute-of-technology-iit-jodhpur-1602700', true),
  ('696409fbbb217904d0d80436', 'Kaggle Knight', '2026-01-12T00:00:00.000Z', null, 'https://unstop.com/hackathons/kaggle-knight-indian-institute-of-technology-iit-jodhpur-1602694', true),
  ('69640b909ca5d7968fed570d', 'GameJam', '2026-01-16T00:00:00.000Z', null, 'https://unstop.com/hackathons/gamejam-indian-institute-of-technology-iit-jodhpur-1602668', true),
  ('69640b6e9ca5d7968fed5709', 'Micromouse Autonomous Bot Making Competition', '2026-01-16T00:00:00.000Z', null, 'https://unstop.com/competitions/micromouse-autonomous-bot-making-competition-indian-institute-of-technology-iit-jodhpur-1602683', true),
  ('69640b399ca5d7968fed5701', 'Boat Racing', '2026-01-16T00:00:00.000Z', null, 'https://unstop.com/competitions/boat-racing-indian-institute-of-technology-iit-jodhpur-1602691', true),
  ('69640b1b9ca5d7968fed56fd', 'Pick and Place', '2026-01-16T00:00:00.000Z', null, 'https://unstop.com/competitions/pick-and-place-indian-institute-of-technology-iit-jodhpur-1602672', true),
  ('69640ae69ca5d7968fed56f5', 'Line Follower Bot Competition', '2026-01-16T00:00:00.000Z', null, 'https://unstop.com/competitions/line-follower-bot-competition-prometeo26-indian-institute-of-technology-iit-jodhpur-1602676', true),
  ('69640ace9ca5d7968fed56f1', 'Capture the Flag (CTF)', '2026-01-16T00:00:00.000Z', null, 'https://unstop.com/hackathons/capture-the-flag-prometeo26-indian-institute-of-technology-iit-jodhpur-1612072', true),
  ('69640ab59ca5d7968fed56ed', 'Robo Soccer', '2026-01-16T00:00:00.000Z', null, 'https://unstop.com/competitions/robo-soccer-indian-institute-of-technology-iit-jodhpur-1602714', true),
  ('69640a959ca5d7968fed56e9', 'RC Electric Racing', '2026-01-16T00:00:00.000Z', null, 'https://unstop.com/competitions/rc-electric-racing-indian-institute-of-technology-iit-jodhpur-1602706', true),
  ('69640a6a9ca5d7968fed56e5', 'Drone Cargo', '2026-01-16T00:00:00.000Z', null, 'https://unstop.com/competitions/drone-cargo-challenge-indian-institute-of-technology-iit-jodhpur-1602666', true),
  ('69640a259ca5d7968fed56e1', 'Robowars', '2026-01-16T00:00:00.000Z', null, 'https://unstop.com/competitions/robowars-indian-institute-of-technology-iit-jodhpur-1602692', true),
  ('69640bf09ca5d7968fed5719', 'Code Wars', '2026-01-17T00:00:00.000Z', null, 'https://unstop.com/hackathons/code-wars-indian-institute-of-technology-iit-jodhpur-1602677', true),
  ('69640b559ca5d7968fed5705', 'Battle of Traders', '2026-01-17T00:00:00.000Z', null, 'https://unstop.com/competitions/battle-of-traders-indian-institute-of-technology-iit-jodhpur-1602687', true)
on conflict (external_id) do nothing;

insert into members (full_name, role_label, department, photo_url, linkedin_url, email, sort_order, is_placeholder) values
  ('Yash Golani', 'General Secretary ACAC', 'Student Affairs', '/images/team/yash.jpeg', 'https://www.linkedin.com/in/yash-golani-144210106/', 'gensecy_acac@iitj.ac.in', 1, false),
  ('Tharakadatta G Hegde', 'General Secretary SS', 'Student Affairs', '/images/team/tharak.jpeg', 'https://www.linkedin.com/in/tharakadattahegde/', 'gensecy_ss@iitj.ac.in', 2, false),
  ('Manas Chechani', 'General Secretary SAC', 'Student Affairs', '/images/team/manas.jpeg', 'https://www.linkedin.com/in/manas-chechani-1452ab253/', 'gensecy_sac@iitj.ac.in', 3, false),
  ('Sambhav Jha', 'VP BCCA', 'Student Affairs', '/images/team/sambhav.jpeg', 'https://www.linkedin.com/in/sambhav-jha-61412528a/', 'b23ee1092@iitj.ac.in', 4, false),
  ('Dhruva Kumar Kaushal', 'Coordinating Team', 'Student Team', '/images/team/dhruva.jpeg', 'https://www.linkedin.com/in/dhruvakkaushal/', 'b22ai017@iitj.ac.in', 5, false),
  ('Rhythm Baghel', 'Coordinating Team', 'Student Team', '/images/team/rhythm.jpeg', 'https://www.linkedin.com/in/rhythm-baghel-80675a25a/', 'b22cs042@iitj.ac.in', 6, false),
  ('Anuj Patil', 'Coordinating Team', 'Student Team', '/images/team/anuj.jpeg', 'https://www.linkedin.com/in/anuj-vijay-patil/', 'b22ee010@iitj.ac.in', 7, false),
  ('Mrudhul Tula', 'Core Team', 'Student Team', '/images/team/mrudhul.jpeg', 'https://www.linkedin.com/in/tula-mrudhul/', 'b23ee1076@iitj.ac.in', 8, false),
  ('Sohom Sarkar', 'Core Team', 'Student Team', '/images/team/sohom.jpeg', 'https://www.linkedin.com/in/sohom-sarkar-598b9b2aa/', 'b23ee1099@iitj.ac.in', 9, false),
  ('Agam Harpreet Singh', 'Core Team', 'Student Team', '/images/team/agam.jpeg', 'https://www.linkedin.com/in/agam-harpreet-singh/', 'b23cm1004@iitj.ac.in', 10, false),
  ('Goutham A.S', 'Core Team', 'Student Team', '/images/team/goutham.jpeg', 'https://www.linkedin.com/in/goutham-a-s-93b30b312/', 'b23ee1024@iitj.ac.in', 11, false),
  ('Tashir Ahmed', 'Core Team', 'Student Team', '/images/team/tashir.jpeg', 'https://www.linkedin.com/in/tashir-ahmed-5315b128b/', 'b23me1074@iitj.ac.in', 12, false);
