// Builds supabase/seed.sql from the imported data, and supabase/bootstrap.sql
// (every migration + the seed) for pasting into the Supabase SQL editor, since
// the Supabase CLI cannot run on this machine.
//
//   node scripts/build-seed.mjs
//
// Sources:
//   data-official/events.json, members.json  — the official site (see SOURCE.md)
//   data-official/inventory.json, projects.json — from the Endurance build
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const read = (p) => JSON.parse(fs.readFileSync(path.join(root, p), "utf8"));

const q = (v) =>
  v === null || v === undefined ? "null" : `'${String(v).replaceAll("'", "''")}'`;
const arr = (a) => `array[${a.map(q).join(", ")}]::text[]`;
const json = (o) => `${q(JSON.stringify(o))}::jsonb`;

const out = [
  "-- Generated by scripts/build-seed.mjs. Edit the JSON in data-official/, not this file.",
  "",
];

// ---- inventory -------------------------------------------------------------
const items = read("data-official/inventory.json");
out.push("insert into items (code, name, variant, category, description, specs, qty_total, qty_available, bench_only) values");
out.push(
  items
    .map(
      (i) =>
        `  (${q(i.code)}, ${q(i.name)}, ${q(i.variant)}, ${q(i.category)}, ${q(i.description)}, ${json(i.specs ?? [])}, ${i.qtyTotal}, ${i.qtyAvailable}, ${i.benchOnly ? "true" : "false"})`,
    )
    .join(",\n") +
    "\non conflict (code) do update set name = excluded.name, variant = excluded.variant, category = excluded.category, description = excluded.description, specs = excluded.specs, bench_only = excluded.bench_only;",
);
out.push("");

// ---- projects --------------------------------------------------------------
const projects = read("data-official/projects.json");
out.push("insert into projects (slug, title, subtitle, body, tags, year, sort_order, published) values");
out.push(
  projects
    .map((p, n) => `  (${q(p.slug)}, ${q(p.title)}, ${q(p.subtitle)}, ${q(p.body)}, ${arr(p.tags)}, ${p.year}, ${n + 1}, true)`)
    .join(",\n") + "\non conflict (slug) do nothing;",
);
out.push("");

// ---- events ----------------------------------------------------------------
const stripTags = (html) => html.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
const events = read("data-official/events.json");
out.push("insert into events (external_id, title, starts_at, description, link_url, published) values");
out.push(
  events
    .sort((a, b) => a.date_event.localeCompare(b.date_event))
    .map((e) => {
      const link = e.description.match(/href="([^"]+)"/)?.[1] ?? null;
      const text = stripTags(e.description);
      // The official descriptions are just the event name wrapped in a link.
      const description = text && text !== e.name ? text : null;
      return `  (${q(e._id)}, ${q(e.name)}, ${q(e.date_event)}, ${q(description)}, ${q(link)}, true)`;
    })
    .join(",\n") + "\non conflict (external_id) do nothing;",
);
out.push("");

// ---- members ---------------------------------------------------------------
const members = read("data-official/members.json");
out.push("insert into members (full_name, role_label, department, photo_url, linkedin_url, email, sort_order, is_placeholder) values");
out.push(
  members
    .map(
      (m) =>
        `  (${q(m.name)}, ${q(m.role)}, ${q(m.department)}, ${q("/images/" + m.photo)}, ${q(m.linkedin)}, ${q(m.email)}, ${m.sort_order}, false)`,
    )
    .join(",\n") + ";",
);
out.push("");

const seed = out.join("\n");
fs.writeFileSync(path.join(root, "supabase/seed.sql"), seed);

const migDir = path.join(root, "supabase/migrations");
const migrations = fs
  .readdirSync(migDir)
  .filter((f) => f.endsWith(".sql"))
  .sort()
  .map((f) => `-- ==== ${f} ====\n${fs.readFileSync(path.join(migDir, f), "utf8")}`);
// One transaction, so a failure part-way leaves an empty database that can
// simply be re-run, instead of half a schema that collides on the second try.
fs.writeFileSync(
  path.join(root, "supabase/bootstrap.sql"),
  ["begin;", ...migrations, "-- ==== seed.sql ====", seed, "commit;"].join("\n\n"),
);

console.log(`seed: ${items.length} items, ${projects.length} projects, ${events.length} events, ${members.length} members`);
